a = int(input("Enter first Number:" ))
b = int(input("Enter second Number:" ))
Addition=a+b
Subtraction=a-b
Multiplication=a*b
Division=a/b
print ("Addition =",Addition)
print ("Subtraction =",Subtraction)
print ("Multiplication =",Multiplication)
print ("Division =",Division)
